# Generated by Django 5.1.4 on 2025-01-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_vehicletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_vehicletype',
            old_name='vehicle_name',
            new_name='vehicletype_name',
        ),
    ]
