# Generated by Django 5.1.4 on 2025-01-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_rename_vehicle_name_tbl_vehicletype_vehicletype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_subject', models.CharField(max_length=30)),
                ('Complaint_complaint', models.CharField(max_length=30)),
            ],
        ),
    ]
