# Generated by Django 5.1.4 on 2025-01-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
    ]
