# Generated by Django 5.1.4 on 2025-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_status', models.IntegerField(default=0)),
                ('Request_date', models.DateField(auto_now_add=True)),
                ('Request_fordate', models.DateField()),
            ],
        ),
    ]
