# Generated by Django 5.1.4 on 2025-02-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Request',
        ),
    ]
