# Generated by Django 5.1.4 on 2025-02-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_renter_renter_status'),
        ('Renter', '0007_tbl_vehiclegallery'),
        ('User', '0004_delete_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_status', models.IntegerField(default=0)),
                ('Request_date', models.DateField(auto_now_add=True)),
                ('Request_fordate', models.DateField()),
                ('Request_startKm', models.CharField(max_length=30)),
                ('Request_endKm', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter.tbl_vehicle')),
            ],
        ),
    ]
