# Generated by Django 5.2 on 2025-04-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_renter_renter_status'),
        ('Renter', '0007_tbl_vehiclegallery'),
        ('User', '0008_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_data', models.IntegerField()),
                ('user_review', models.CharField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter.tbl_vehicle')),
            ],
        ),
    ]
