# Generated by Django 5.1.4 on 2025-02-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_vehicle',
            old_name='vehicletype_name',
            new_name='vehicletype',
        ),
    ]
