# Generated by Django 5.1.4 on 2025-02-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0002_rename_vehicletype_name_tbl_vehicle_vehicletype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Vehicle',
        ),
    ]
