# Generated by Django 5.1.4 on 2025-02-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0011_delete_tbl_complaint'),
        ('Guest', '0004_tbl_renter_renter_status'),
        ('Renter', '0003_delete_tbl_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_name', models.CharField(max_length=30)),
                ('Vehicle_image', models.FileField(upload_to='Assets/File/Vehicle')),
                ('Vehicle_minkm', models.CharField(max_length=30)),
                ('Vehicle_minrate', models.CharField(max_length=30)),
                ('Vehicle_kmrate', models.CharField(max_length=80)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_renter')),
                ('vehicletype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_vehicletype')),
            ],
        ),
    ]
