# Generated by Django 5.1.4 on 2025-02-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0005_alter_tbl_vehicle_vehicle_image_tbl_vehiclegallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_VehicleGallery',
        ),
    ]
