# Generated by Django 5.1.4 on 2025-02-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0006_delete_tbl_vehiclegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_VehicleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_photo', models.FileField(upload_to='Assets/File/Vehiclegallery/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter.tbl_vehicle')),
            ],
        ),
    ]
