# Generated by Django 5.1.4 on 2025-01-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='User_photo',
            field=models.FileField(default=2, upload_to='Assets/File/User'),
            preserve_default=False,
        ),
    ]
