# Generated by Django 5.1.4 on 2025-01-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_delete_tbl_complaint'),
        ('Guest', '0002_tbl_user_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Renter_name', models.CharField(max_length=30)),
                ('Renter_Email', models.CharField(max_length=30)),
                ('Renter_contact', models.CharField(max_length=30)),
                ('Renter_address', models.CharField(max_length=80)),
                ('Renter_Password', models.CharField(max_length=30)),
                ('Renter_photo', models.FileField(upload_to='Assets/File/Renter')),
                ('Renter_proof', models.FileField(upload_to='Assets/File/Renter')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
