# Generated by Django 5.1.4 on 2025-01-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_renter',
            name='Renter_status',
            field=models.IntegerField(default=0),
        ),
    ]
